
# @schema
# description: Apache Kafka configuration (cluster + topics)
# type: object
# @schema
kafka:
  # @schema
  # description: Logical name of the Kafka cluster
  # type: string
  # default: kafka
  # @schema
  clusterName: "kafka"
  # @schema
  # description: Topics to create on the cluster
  # type: array
  # items: 
  #   properties: 
  #     topicName:
  #       type: string
  #       description: Kafka topic name
  #       required: true
  #     partitions:
  #       description: Number of partitions for the topic
  #       type: integer
  #       minimum: 1
  #       default: 3
  #       required: true
  #     replicas:
  #       description: Replication factor for the topic
  #       type: integer
  #       minimum: 1
  #       default: 1
  #       required: true
  #   type: object
  # @schema
  topics:
  - topicName: "first-topic"
    partitions: 3
    replicas: 1    